#
# This config.toml is an example and based on the ananke theme
# https://github.com/theNewDynamic/gohugo-theme-ananke/.
#
# If you use a different theme, you might need to change the content of config.toml
# to your liking.
#

#
# Theme setup
#
# If you use go mod to install your theme, you must use the URL of the theme.
# If your theme is in the themes directory, you just need to specify its name.
#
#theme = "ananke"
theme = "gohugo-theme-ananke"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
baseurl = "/"
title = "GitLab Pages and Hugo"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
languageCode = "es"
resourceDir = "../resources"
relativeURLs = true 



DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
 [languages.es]
    title = "Ecof data"
    weight = 1
    contentDir = "content/es"
  
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/JosMnera2"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
